### ISSUE TITLE
Delete from localstorage

### ISSUE THREAD

**Issue by ravimarici** [ravimarici/saadh_assessment_react_app#5]
Delete from localstorage

**Comment by ravimarici** [comment]
@Saadhmarici 

in Create.js update the localStorage with updated filtered Blogs like below code.

![image](https://user-images.githubusercontent.com/102516623/189575576-81957cd6-b245-452d-a519-c9cdb306c101.png)

**Comment by Saadhmarici** [comment]
Completed delete from Local Storage
